CREATE DATABASE planingdb CHARACTER SET utf8;

USE planingdb;

CREATE TABLE User (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
givenName varchar(512) NOT NULL,
surname varchar(512) NOT NULL,
email varchar(254) NOT NULL UNIQUE,
password varchar(254) NOT NULL,
createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=InnoDB;

CREATE TABLE Game (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
description varchar(512) NOT NULL,
maxParticipants TINYINT UNSIGNED DEFAULT 4,
result TINYINT UNSIGNED,
createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=InnoDB;

CREATE TABLE GameInstance (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
userID INT UNSIGNED NOT NULL,
gameID INT UNSIGNED NOT NULL,
playedValue varchar(254),
createdAt timestamp DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)ENGINE=InnoDB;